### ISSUE TITLE
Rofi

### ISSUE THREAD

**Issue by tororutsu** [samedamci/biual-dot-conf#2]
Hey buddy, I honestly dont have an issue, i was just wondering how you got rofi to work!
I can type rofi -show run in the terminal and it works with no problem, but when I put it in my sxhkdrc, it just doesnt work! can you drop me some advice please lol

**Comment by wzykubek** [comment]
I set 

```
super + d
    rofi -show drun
```

This tab indentation is required to sxhkd binding work. After set it you must restart sxhkd. Are you sure you done this?

**Comment by tororutsu** [comment]
It actually was failing due to locale :( sad lol.
